[2017-05-10 14:03:10 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 327, in data
    _value = item.content[_field.id]
KeyError: 'status'

[2017-05-10 14:03:10 view.tree.model] ERROR Error, data is: 
[2017-05-10 14:03:10 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 327, in data
    _value = item.content[_field.id]
KeyError: 'status'

[2017-05-10 14:41:19 view.tree.model] ERROR Error, data is: 
[2017-05-10 14:41:19 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 327, in data
    _value = item.content[_field.id]
KeyError: 'status'

[2017-05-10 14:41:19 view.tree.model] ERROR Error, data is: 
[2017-05-10 14:41:19 view.tree.model] ERROR Traceback (most recent call last):
  File "/Users/zhaojingping/PycharmProjects/AuxiTools/test/OrcTestToolsKit/OrcView/Lib/LibTree.py", line 327, in data
    _value = item.content[_field.id]
KeyError: 'status'

